### ISSUE TITLE
pipline failed

### ISSUE THREAD

**Issue by km-2021** [d3b-center/annoFuse#102]
#### What data file(s) does this issue pertain to?
expression files with rsem

#### Put your question or report your issue here.
I run the annoFuse with hg38p14, but failed with the following command:

Using GeneSymbol as id variables
1: The following named parsers don't match the column names: CDS_LEFT_ID, CDS_LEFT_RANGE, CDS_RIGHT_ID, CDS_RIGHT_RANGE, PROT_FUSION_TYPE, FUSION_MODEL, FUSION_CDS, FUSION_TRANSL, PFAM_LEFT, PFAM_RIGHT 
2: Expected 2 pieces. Missing pieces filled with `NA` in 29 rows [1, 2, 3, 4, 5,
6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
3: Expected 2 pieces. Missing pieces filled with `NA` in 29 rows [1, 2, 3, 4, 5,
6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
4: Expected 2 pieces. Missing pieces filled with `NA` in 36 rows [1, 2, 3, 4, 5,
6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
5: Expected 2 pieces. Missing pieces filled with `NA` in 31 rows [1, 2, 4, 6, 7,
8, 9, 10, 11, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, ...]. 
6:  fusion_filtering_QC(standardFusioncalls = standardFusioncalls,  で: 
  No fusion calls with annotation: GTEx_RecurrentNo fusion calls with annotation: NormalNo fusion calls with annotation: BodyMapNo fusion calls with annotation: ConjoinG
7:  annoFuse::expression_filter_fusion(standardFusioncalls = fusionQCFiltered, : 
  Not all genes in expression file. Adding genes unique to fusion in output.

**Comment by jharenza** [comment]
Hi. Which fusion callers and versions are you using? Please also send test input files, the commands used, and your session info to help diagnose the problem. Some of the above are only warnings and are expected.
