### ISSUE TITLE
Read expression file

### ISSUE THREAD

**Issue by km-2021** [d3b-center/annoFuse#103]
#### Put your question or report your issue here.

Is the following code correct for loading the Expression file?

expressionFile <- ("expressionfilename.gz")

**Comment by jharenza** [comment]
>expressionFile <- ("expressionfilename.gz")

Depending on the format of your file, and the libraries you have installed you would read in the file various ways:

using tidyverse and a tsv:

```R
expressionFile <- read_tsv("expressionfilename.tsv.gz")
```

using base R reading in an RDS file:
```R
expressionFile <- readRDS("expressionfilename.RDS.gz")
```

using base R reading in an RData file:
```R
load("expressionfilename.RDA.gz", verbose = TRUE)
```
