### ISSUE TITLE
Error with annotation

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#104]
@kgaonkar6 , @jharenza  
Y have error for annotated fusion call from arriba and Star-fusion. Y use annoFuse:

Warning messages:
1: Expected 2 pieces. Missing pieces filled with `NA`

_Originally posted by @serignebasse in https://github.com/d3b-center/annoFuse/issues/85#issuecomment-1906887707_

**Comment by serignebasse** [comment]
thanks you @jharenza, y use annotate_fusion_calls: Function to annotate fusion calls. Y tried with Example star fusion and arriba fusion input files found in annoFuseData  but y get same error

**Comment by federicomarini** [comment]
I am not entirely sure the message you obtained is indicative of an error per se, but it just seems to be a warning.

Could you provide us with some form of an example we can try to reproduce on our ends? Either a self contained snippet using the example data (if you have the message on that) or the code&data you are using when the message is triggered.

**Comment by serignebasse** [comment]
@federicomarini  it is the same error when I use the example data in annoFuse.  Y used the code and example data in the documentation without changing anything. But Y get this error.  Y don't have results.

**Comment by serignebasse** [comment]
the error is in the Standardised function Y thinks, like:
standardizedArriba<-fusion_standardization(fusion_calls = fusionfileArriba, caller = "ARRIBA", tumorID ='tumorID')

**Comment by federicomarini** [comment]
I just tested running the whole set of examples on the package as it is now in the `master` codebase, and I was not able to reproduce the error you mention.
Can you please try to update your local installation to the latest version?

<img width="315" alt="image" src="https://github.com/d3b-center/annoFuse/assets/7447478/c5e8a3c3-5b69-4e62-8f8f-83e6448bb4ca">

Again, if all you see is 

```
Warning messages:
1: Expected 2 pieces. Missing pieces filled with NA
```

that is just a warning message. Some fields which were left empty has likely become an `NA`.

@jharenza do you have the same experience with this?
