### ISSUE TITLE
How to understand FusionName

### ISSUE THREAD

**Issue by ShixiangWang** [d3b-center/annoFuse#105]
Dear developers,

I found data containing FusionName like `CTSC--CTSC(13553)/GAPDHP70(34942)`, how should I understand here CTSC twice and `13553`/`34942`?

Best,

Shixiang

**Comment by jharenza** [comment]
Hi @ShixiangWang - so sorry for the delay - the fusion calling is being done upstream of this, and so this may be related to either star-fusion or arriba and I would suggest checking their docs. Sometimes, this suggests a duplication event in the gene, but I am not 100% sure about the above fusion.

**Comment by jharenza** [comment]
Closing this, as is an upstream question.
