### ISSUE TITLE
domain plots and recurrence plots for shiny_fuse

### ISSUE THREAD

**Issue by kgaonkar6** [d3b-center/annoFuse#12]
# Description 

General issue:
Updates for plots for use in shiny_fuse and app

Specifics:
Domain plots

- [x] add domain legend to the bottom ( internal to annoFuse ) 
- [x] add filtering inside the plot_breakpoint()
- [x] add Sample param to plot_breakpoint()
- [x] if non-coding genes in fusion add just exon gene structure and if intergenic add genomic in x axis
- [ ] if plotting breakpoints across Samples then need to have interactive pop up of Sample name when the user hovers over the line  (to-do for later)

Recurrent fusion/genes plots:

- [x] bigger x axis labels ( internal to annoFuse )
- [x] titles for plots ( internal to annoFuse )
- [x] these plots for recurrent plots/ summary plot need grouping variable, we need to discuss ways to have that information added/provided in the app/shiny_fuse function (shiny_fuse)
- [x] fix xlim on right plot
- [x] right plot legend - move to bottom

How will work on this:
@kgaonkar6  will work on the topics which are "internal to annoFuse" functions 
@federicomarini can take a look at the "shiny_fuse" specific tasks

**Comment by jharenza** [comment]
- [x] For intergenic fusions, can you still enable plotting of the breakpoint within the other gene?

**Comment by kgaonkar6** [comment]
Sample selection has replaced this for now
- if plotting breakpoints across Samples then need to have interactive pop up of Sample name when the user hovers over the line (to-do for later)

Other points from this issue have been completed. I think we can close this to open 1 if this hover feature is prioritized later
