### ISSUE TITLE
Examples to showcase the usage of functions

### ISSUE THREAD

**Issue by federicomarini** [d3b-center/annoFuse#17]
Full set of examples for the functions exported

- [x] aggregate_fusion_calls
- [x] annoFuse_single_sample
- [x] annotate_fusion_calls
- [x] called_by_n_callers
- [x] expression_filter_fusion
- [x] fusion_driver
- [x] fusion_filtering_QC
- [x] fusion_multifused
- [x] fusion_standardization
- [x] get_Pfam_domain
- [x] groupcount_fusion_calls
- [x] plot_breakpoints
- [x] plot_recurrent_fusions
- [x] plot_recurrent_genes
- [x] plot_summary
- [x] report_fuse
- [x] samplecount_fusion_calls
- [x] shiny_fuse
- [x] theme_publication
- [x] zscored_annotation

**Comment by federicomarini** [comment]
First update: many functions are either complete or partially there - I would need to enter some reasonable values for the examples and/or for the defaults.

Plus, well, have the files to be still standardized as input for the call to standardize the fusion 😉 

-> working in branch `exemplary`

**Comment by kgaonkar6** [comment]
I missed this issue and in my recent PR I've added example for the new plot_breakpoint function and annoFuse_single_sample function

**Comment by federicomarini** [comment]
This is no problem at all, I opened it just recently!
Incidentally, these functions were not done yet in their examples, so it will be perfect to integrate them together!
I'll probably try to first merge then your branch into `exemplary`, and then proceed in merging to `master`

**Comment by kgaonkar6** [comment]
Sounds good

**Comment by kgaonkar6** [comment]
can we close this since the list seems to be complete?

**Comment by federicomarini** [comment]
With much pleasure!
