### ISSUE TITLE
table summary errors

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#19]
Branches tested: `loading_progress` and `exemplary`

```
Insufficient values in manual scale. 6 needed but only 3 provided.
```

and
  
```
Insufficient values in manual scale. 4 needed but only 3 provided.` are errors when doing grouping.
```

Perhaps also rename `TableSummary` to `Recurrent Fusions` and `TableExplorer` to `Fusion Explorer`.

@federicomarini

**Comment by federicomarini** [comment]
I was taking `TableSummary` as it was the output of `plot_summary` -> maybe then `FusionSummary`?

`TableExplorer` -> `FusionExplorer`, ✅ 

Re: the three values, this might be gone in the devel branches. We had enforced the scale manually, but using only 3 colors. So this means for factors with 6 levels, that would not be good.

**Comment by jharenza** [comment]
sure, `FusionSummary` sounds good!

**Comment by jharenza** [comment]
We will need to join `annoFuse/inst/extdata/PutativeDriverAnnoFuse_test_v14.tsv` with clinical information for this to be meaningful.

**Comment by federicomarini** [comment]
Re: color palette issues, should be done in https://github.com/d3b-center/annoFuse/commit/1f4e3b060af7f5c93284f3343778a6f60b2eb9de
