### ISSUE TITLE
additional column features for FusionExplorer

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#23]
Few suggestions:
- [ ] Freeze header row and create scroll bar within table instead of on entire app page
- [ ] Enable the user to select only columns of interest for viewing / remove columns that are bulking up the table

**Comment by federicomarini** [comment]
1. Could be possible with FixedHeader and a clever setting for scrollX.
2. Ideally a filter on the sidebar, with a few columns preselected, and the possibility to re-add all the ones that are in the file?

**Comment by jharenza** [comment]
Sounds great!

**Comment by federicomarini** [comment]
Both looks like got addressed in https://github.com/d3b-center/annoFuse/commit/e3dd64ba2cf3c202a9bed5799251cc20fd0a3bc6

Currently selecting the first 10 columns, but it can be changed to more informative ones, in case you can propose a minimal set of "must-be-shown" ones ;)

**Comment by jharenza** [comment]
added some default columns to display in #32
