### ISSUE TITLE
download table not working

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#24]
When I try to download the table, I get an RStudio popup but no table being saved. 

Also, I noticed that when I try to copy to clipboard after filtering, say, for `in-frame` `fusion_type`, it only copies the visible rows (25) instead of the true selection (1,613) of 4,462. In addition to this, when pasting, the output does not paste properly because of blank cells. Maybe we remove `copy` altogether right now?

**Comment by federicomarini** [comment]
This issue is somewhat weird.
Not showing up when using the DT in a normal interactive session, but it does when in shiny. 

Workaround possibly shown in https://github.com/d3b-center/annoFuse/commit/e3dd64ba2cf3c202a9bed5799251cc20fd0a3bc6, where the paging functionality is disabled - but using a fixed amount of height prevents from having km (or miles)-long tables!

Could you please try it outside RStudio (in any other browser) @jharenza? It is working fine for me there (Safari/FF/Chrome were tested)

**Comment by jharenza** [comment]
Download in browser works, but also only downloading the "visible" table (25 rows) and not the entire filtered table. Can this be fixed?

Copying from browser still broken (does not tab-separate). Please remove this button.

**Comment by federicomarini** [comment]
Works fine for me in the current `exemplary` branch - where all rows are actually shown.
In the code there should be a line with `paging = FALSE`.

Copying from browser seems to work for me, at least so it seems:

In RStudio: 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/7447478/91092910-faf39780-e658-11ea-8eb6-44766fb99d78.png">

-> it looks like the double space is where the tab comes into play

In SublimeText:

<img width="955" alt="image" src="https://user-images.githubusercontent.com/7447478/91092997-178fcf80-e659-11ea-99f4-52d23018e282.png">

-> there the spacing is even more evident

**Comment by jharenza** [comment]
Ahh, I was copying to excel, as I imagine most GUI users will be doing it that way, and not familiar with text editors. Actually, I was having some problems with some of the functions not working because I wasn't restarting RStudio - let me check this again just to be sure.

**Comment by jharenza** [comment]
Yes, still an error with copying to excel:
<img width="657" alt="Screen Shot 2020-08-24 at 7 46 44 PM" src="https://user-images.githubusercontent.com/207034/91107158-93cae880-e642-11ea-9af5-3a1ec53ac05b.png">

**Comment by federicomarini** [comment]
Interesting, these look like are rows where there's an NA?

<img width="865" alt="image" src="https://user-images.githubusercontent.com/7447478/91139084-87c94000-e6af-11ea-913c-9d22a4c52140.png">

But the NA looks like it is in the raw text file (PutativeOncogenicFusion.tsv).

I'd say for Excel users should be fine with the "download to" option.

Should I just remove the "Copy" button? I'd argue that this is the most useful for us text-editors-affine people (i.e. us :D )

**Comment by federicomarini** [comment]
(good news is indeed that the Download to Excel works as it should!)

**Comment by jharenza** [comment]
> But the NA looks like it is in the raw text file (PutativeOncogenicFusion.tsv).
> 
> I'd say for Excel users should be fine with the "download to" option.
> 
> Should I just remove the "Copy" button? I'd argue that this is the most useful for us text-editors-affine people (i.e. us :D )

Yes, they are NAs that don't get captured in excel with copy. I agree it is useful for text editors for us, so what about this - how about you keep it in the package, but remove from stand-alone web server?

**Comment by federicomarini** [comment]
I'd be rather blunt here and remove it - unless I find a way to auto-detect whether it runs on a server or local.
Are we really thinking of copy-pasting (to the simple clipboard) so often? Export to excel to re-read in R would be not that far away in terms of operations needed...

**Comment by jharenza** [comment]
Ok, just remove then.

**Comment by federicomarini** [comment]
Will be solved once https://github.com/d3b-center/annoFuse/pull/33 is in 🍷

**Comment by federicomarini** [comment]
Closing via #33
