### ISSUE TITLE
add text for "about" info in shiny app

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#25]
Hi @federicomarini - this is a quick writeup of some of the things we can add to the text boxes.

I think we can have 2 sections in `About`, then `News`, in a separate tab, and `Contact` in another tab, if possible.

## About FusionExplorer
FusionExplorer is an interactive way to explore the putative oncogenic fusion results from annoFuse. 
**Required input:** `PutativeOncogenicFusion.tsv`
**Features:** 
_Filtering_: Select a column and enter one or more attributes on which to filter the rows.
_Data export_: Export the filtered table using the download button above.
_Fusion visualization_: To view the gene fusion, exons, protein domains, and breakpoints:
 1. Load the `exons` and `pfam` domains by clicking the buttons on the upper right side. 
 2. Select any row in the data table to visualize that specific fusion. Plots for the 5' gene, 3' gene, and both genes will be generated to the right of the table.

_Plot export_: To save the fusion plot, select the green download arrow below the plot.

## About FusionSummary
**Features:** 
_Recurrent fusions_: To analyze recurrent fusions within a cohort:
 1. To the left of the table, select a `Grouping Column`. This will be the column used for analysis of recurrent fusions. For example, if your dataset has multiple histologies and you are interested in recurrent fusions by histology, this value would be histology.
 2. Select the number of top fusions to display in the plot.
 3. Select a `Counting column`. This is usually a patient-level identifier.

_Fusion visualization_: To view the recurrent fusions results, click on the `FusionSummary` tab, where plots for recurrent fusions and recurrently-fused genes will be generated.
_Plot export_: To save the fusion plot, select the green download arrow below the plot.

## News
[Date of Launch]. Welcome to ShinyFuse, an application for exploration of fusion output derived from [annoFuse](https://github.com/d3b-center/annoFuse)! The purpose of this application is Please take the tour, activated by clicking on the question mark in the upper right corner, and test out the demo dataset by clicking on `Load demo data` in the upper left corner. Thanks for visiting!

## Contact
Please file application issues, suggestions, or bug reports [here](https://github.com/d3b-center/annoFuse/issues).

**Comment by federicomarini** [comment]
Looks good as a start, thanks a lot!
I'll try to assign each portion to the dedicated ui anchoring element.

**Comment by federicomarini** [comment]
> I think we can have 2 sections in About, then News, in a separate tab, and Contact in another tab, if possible.

Can be done. I was thinking of having all in one, but in the end we can do what we want (more 1st level tabs, more sub-tabs, just one with md sections...)

**Comment by federicomarini** [comment]
A first full round of the tour is present in https://github.com/d3b-center/annoFuse/tree/takeatour, feel free to enjoy the guided tour!

**Comment by federicomarini** [comment]
`takeatour` is merged now, so it is safe to close this one 😉

**Comment by jharenza** [comment]
I think we want to remove `The purpose of this application is…` from the top of the About tab.

Also noticing now we have some additional buttons, so maybe we should explain those above?

**Comment by federicomarini** [comment]
On it.

I'll see what is missing from the older tour and fill in where needed

**Comment by federicomarini** [comment]
Done in #52!
