### ISSUE TITLE
update default columns to display in shinyFuse

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#32]
Let's use these:
```
Sample
FusionName
LeftBreakpoint
RightBreakpoint
Fusion_Type
JunctionReadCount
SpanningFragCount
Confidence
CalledBy
```

**Comment by federicomarini** [comment]
Shall we maybe also add at least `Gene1A` and `Gene1B`? 
These trigger the whole side content right of the table.

**Comment by federicomarini** [comment]
Updated in https://github.com/d3b-center/annoFuse/commit/20f2e4b15b2ed6aa2a80450bc5a4c42946201d01, to enable the right hand side content to be ready to use
