### ISSUE TITLE
breakpoint plots - some error out

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#37]
Branch: `takeatour`

Some rows error out and default back to plotting multiple breakpoints. For example: sample `BS_17WYVEEC` `KIAA1549--BRAF` fusion gives error:

```
Warning: Error in plot_breakpoints: domainDataFrame is empty after selecting for fusionname 
  [No stack trace available]
```

and plot:

[annofuse_bpboth.pdf](https://github.com/d3b-center/annoFuse/files/5126774/annofuse_bpboth.pdf)

Related: the plot render here is smushed. @kgaonkar6

**Comment by federicomarini** [comment]
Can you try to see if you get the breakpoint plot for that exact fusion?
My suspicion is that the error comes from the plotting function itself - i.e. I had some similar errors when the fusion name contained non-conventional names (that probably have then no entries in the domainDataFrame?)

**Comment by federicomarini** [comment]
Using the branch `exemplary`, where `takeatour` now is in:

- I could not reproduce this in shiny -> plot is generated as expected
- I tried also to use "offline" just plot_breakpoints, and that also seems to work

Can you try from a fresh session maybe?
Thanks!

**Comment by jharenza** [comment]
New session in exemplary branch, still getting those old plots with `BS_17WYVEEC`. @kgaonkar6 can you test?

**Comment by kgaonkar6** [comment]
Works fine for me as well
<img width="1433" alt="Screen Shot 2020-08-26 at 11 20 44 AM" src="https://user-images.githubusercontent.com/34580719/91322905-43f93800-e78e-11ea-94e1-9df0acebecdc.png">

**Comment by kgaonkar6** [comment]
@federicomarini can we add the Sample selection feature to the plots now that the plot_breakpoints has that as the input paramter?
https://github.com/d3b-center/annoFuse/blob/1940612e242902c11b726bab61ee2cec8d87b131/R/plot_breakpoints.R#L39

**Comment by federicomarini** [comment]
I would envision two possible behaviors (at least in shiny):
- checkbox off, only the line is selected -> all plotted, as it is now
- checkbox on -> line is selected anyway, and plots the ones specific to that sampleID
If I recall correctly, your current implementation does exactly that?

**Comment by kgaonkar6** [comment]
Right if sample_id == NULL then plot all in the given input if sample_id != NULL then plot for that specific sample_id only

**Comment by federicomarini** [comment]
Okiedokie.

An example of that is here:
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/7447478/91328055-a2daa380-e7c6-11ea-8729-db87d2988164.png">

You can test it out in `samplespecific_bpplots`.

The checkbox starts ticked, and gets re-ticked upon selection of a new row in the table (the element is re-rendered every new row is picked).
Would that work for you?

**Comment by jharenza** [comment]
@federicomarini - awesome update! I like it!

**Comment by federicomarini** [comment]
Trust me, I just put the widget in the UI, it happens seamlessly because of the nice code re-design from @kgaonkar6!
