### ISSUE TITLE
update breakpoint plots

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#39]
- Add `by row` functionality
- Make plots landscape for printing
- Make plot of both right/left larger for better export.

**Comment by kgaonkar6** [comment]
I'll work on Add by row functionality to the plot_breakpoint function.

@federicomarini  would you be able to take care of the following?
- Make plots landscape for printing
- Make plot of both right/left larger for better export.

Here the pdf that gets downloaded is squished so maybe a longer width can be used to make it more of a landscape view?
[annofuse_bpboth.pdf](https://github.com/d3b-center/annoFuse/files/5137421/annofuse_bpboth.pdf)

**Comment by federicomarini** [comment]
I'll check if it is possible to have the width encoded in clever(er) way to not have all packed into that!

**Comment by federicomarini** [comment]
Done in `per_bk_plots`, as in https://github.com/d3b-center/annoFuse/commit/9857f8e7736547f17b1925e4346cb7aff862630d and subsequent commits 
-> they also fixed the logic for the double plot of breakpoints

**Comment by federicomarini** [comment]
Can be closed after https://github.com/d3b-center/annoFuse/pull/41
