### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#4]
See below when trying to install via GitHub:
```
library(devtools)
install_github("d3b-center/annoFuse")
```

> 
ERROR: dependency ‘EnsDb.Hsapiens.v86’ is not available for package ‘annoFuse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/annoFuse’
Error: Failed to install 'annoFuse' from GitHub:
  (converted from warning) installation of package ‘/var/folders/zs/8g7y6mfs7lldb27t4w906hj1z51wzr/T//RtmpwBuHpZ/filefae15df1672f/annoFuse_0.2.tar.gz’ had non-zero exit status

**Comment by federicomarini** [comment]
Hm, this is a little weird as that package is already correctly listed in the Imports.

Try maybe with

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
install_github("d3b-center/annoFuse", dependencies = TRUE)
```

to force all deps to be installed, and not convert to error the warning that remotes/devtools might throw?

**Comment by kgaonkar6** [comment]
> Hm, this is a little weird as that package is already correctly listed in the Imports.
> 
> Try maybe with
> 
> ```
> Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
> install_github("d3b-center/annoFuse", dependencies = TRUE)
> ```
> 
> to force all deps to be installed, and not convert to error the warning that remotes/devtools might throw?

Installing it separately with `BiocManager::install(“EnsDb.Hsapiens.v86”)` and adding GITHUB_PAT to .Renviron file we made it work for @jharenza 

I'm test installing on a R 3.6.0 docker image to understand/find a work around for the issue.  I tested the above commands but it also errors out similar to the above error. For some reason EnsDb.Hsapiens.v86 doesn't get installed with  install_github("d3b-center/annoFuse", dependencies = TRUE) . I'm installing the dependencies for EnsDb.Hsapiens.v86 which is taking up a bit of time but I guess that should fix it. Any other suggestions?

**Comment by federicomarini** [comment]
Hm, I would suggest to start right away with an image where R-4.0.0 is up and running.
Heavily suggested: the Bioc Docker images - these would be perfect for having both a release and a devel environment (the latter is the one we should use, again if we are oriented towards Bioc submission). Still, both use R-4.0.0 in this release cycle, so this makes it easier ;) 

EDIT
Links: https://www.bioconductor.org/help/docker/
`docker pull  bioconductor/bioconductor_docker:RELEASE_3_11` or `docker pull  bioconductor/bioconductor_docker:devel` should do it

**Comment by kgaonkar6** [comment]
I ran it on docker pull bioconductor/bioconductor_docker:devel with the following R and bioconductor:
R version 4.0.2 Patched (2020-08-13 r79017)  
Platform: x86_64-pc-linux-gnu (64-bit)
Bioconductor version 3.12 (BiocManager 1.30.10)

The issue persists 
```
Downloading GitHub repo d3b-center/annoFuse@HEAD
Skipping 2 packages not available: EnsDb.Hsapiens.v86, ensembldb
```

So the only solution is to download it separately:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("EnsDb.Hsapiens.v86")
```

and then install annoFuse  
```
devtools::install_github("d3b-center/annoFuse", dependencies = TRUE) 
```
To-do @kgaonkar6 add to the Readme

**Comment by federicomarini** [comment]
Hmm, this is odd.
Normally deps are handled correctly, but hey, better safe than sorry.

In the GH Actions these are picked up correctly, see e.g. https://github.com/federicomarini/annoFuse/runs/990566435?check_suite_focus=true in the `Install dependencies` section -> 

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/7447478/90431289-12ff7000-e0c9-11ea-8a8d-9fa6658c190f.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/7447478/90431354-31fe0200-e0c9-11ea-8f91-351548ef5b33.png">

**Comment by kgaonkar6** [comment]
Closing since this seems to fix the issue if it comes up

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("EnsDb.Hsapiens.v86")
and then install annoFuse

devtools::install_github("d3b-center/annoFuse", dependencies = TRUE) 
```
