### ISSUE TITLE
possibly make spanning difference an option

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#40]
Depending on results of comparison between TCGA and PBTA, and potentially another longread dataset with high confidence fusion calls, we can make this an option with default filtering turned on (could make this by read length or not - need to inspect fusion calls in PBTA for false +).

- [ ] @kgaonkar6 Add SpanningDelta to standardFusioncalls

**Comment by federicomarini** [comment]
From what I have seen, the filtering mechanism works nice, so it could be an additional field to work on if it is provided.

**Comment by jharenza** [comment]
I think we can scrap this, as this filtering would be pre-shinyFuse.
