### ISSUE TITLE
add junctionreadcount to plot filter

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#42]
For some reason, this got removed

**Comment by federicomarini** [comment]
I think I did not insert it in the original list of filter to have, but it is now done in `extra_filter` here: https://github.com/d3b-center/annoFuse/commit/83dddbffc47319ce1b04f50a644e1155b0f1f3a1

mini-PR incoming for that 😉

**Comment by federicomarini** [comment]
closed after https://github.com/d3b-center/annoFuse/pull/43
