### ISSUE TITLE
Example data for shiny_fuse

### ISSUE THREAD

**Issue by kgaonkar6** [d3b-center/annoFuse#44]
I've added v16 version of PutativeDriverAnnoFuse files here https://github.com/d3b-center/annoFuse/tree/add_v16_files/inst/extdata

This file needs to be filtered : 
Filter clinical columns to only `integrated_diagnosis` and `broad_histology`
Add BreakpointLocation column with values "Genic","Intergenic" and "Intragenic"

And renamed to just PutativeDriverAnnoFuse.tsv to be used in all examples and shiny_fuse demo data

**Comment by federicomarini** [comment]
I can work on the examples for this branch 

EDIT: oh wait, I see it is all done already, great!

**Comment by kgaonkar6** [comment]
yeah to test if the v16 file / example starfusion,arriba and rsem files work with each function I've added those examples 

So it's now a duplicate to the issue #17 let me know if we can close that and add the checbox for each function here. Thanks!

**Comment by federicomarini** [comment]
We can keep using #17 to track what still is left to be done.
I'll work on the reflowing of the lines to make R CMD check happy (too wide lines would not be rendered nicely)

**Comment by federicomarini** [comment]
closing after merging in https://github.com/d3b-center/annoFuse/tree/add_v16_files
