### ISSUE TITLE
filter dropdown for BreakpointLocation

### ISSUE THREAD

**Issue by kgaonkar6** [d3b-center/annoFuse#47]
## Description

@federicomarini can we add BreakpointLocation as a filter?

Basically by doing the following filters using the demo file we will be able to reproduce the figure in the MS.

sfc <- as.data.frame(sfc[ which(sfc$Fusion_Type == "in-frame" & sfc$BreakpointLocation == "Genic"),])
before runnning 
plot_recurrent_genes(sfc, groupby = "broad_histology", countID = "Kids_First_Participant_ID")

@jharenza should we also make BreakpointLocation a standard fusion call column applicable so that the filter is applicable to all annoFuse output?

**Comment by jharenza** [comment]
> @jharenza should we also make BreakpointLocation a standard fusion call column applicable so that the filter is applicable to all annoFuse output?

sure!

**Comment by federicomarini** [comment]
Will be handled and solved in #49 😉
