### ISSUE TITLE
add support for hg19

### ISSUE THREAD

**Issue by kgaonkar6** [d3b-center/annoFuse#50]
I found pcawg fusion dataset (hg19)
[standardFusioncalls_pcawg.txt](https://github.com/d3b-center/annoFuse/files/5157815/standardFusioncalls_pcawg.txt)
https://dcc.icgc.org/releases/PCAWG/transcriptome/fusion

Just wanted to add here that the hg19 support is mostly important because published PCAWG/DKFZ workflows are hg19 based.

Note: It's already filtered I didn't find raw calls 
This resulted in detection of 3540 fusion events, from these 2268 were detected by
both FusionCatcher/STAR-Fusion and FusionMap (from these 1821 had SV support)
and 1112 were detected by only one method and had SV support. All fusions are
available in Synapse (syn10003873)

Works for most plot except plot_breakpoints since the exon RDS is based on hg38 
For example the RET gene location are as follows 
chr10:43,077,027-43,130,351(GRCh38/hg38)
chr10:43,572,475-43,625,799(GRCh37/hg19)

So using the current exon RDS file the breakpoint is outside the genebody
Gene1A | Gene1B | RightBreakpoint | LeftBreakpoint
-- | -- | -- | --
CCDC6 | RET | 10:61665880 | 10:43612032

**Comment by federicomarini** [comment]
Given that the exons object is the largest one in the package, we'd have to pay extra care in this case...
Maybe something for longer term where we maybe achieve the creation of the exons object either on the fly or in a more lightweight approach?

**Comment by xiucz** [comment]
This may be a good choice.

**Comment by jharenza** [comment]
we will not be pursuing hg19
