### ISSUE TITLE
filtering on shiny server

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#58]
Not sure how to fix this aside from a dropdown, but for instance in the new `BreakpointLocation` column, when searching for `Genic`, all 3 values: `Genic`, `Intergenic`, and `Intragenic` come up in the FusionExplorer, due to the match of `genic` in each term. Thoughts, @federicomarini ?

**Comment by federicomarini** [comment]
The dropdown select input does nothing but picking the levels for showing.
Then, my match is on the *exact* value match, and not grepping for 'genic'. 
So this should be safe, I guess.

**Comment by federicomarini** [comment]
Is there any update on the side of this one @jharenza?

**Comment by jharenza** [comment]
@federicomarini This still doesn't work as I think it should on the demo data - "Genic" does not filter (since Genic is in all 3 of: genic, intergenic, intragenic), but "Intra" filters to 651 rows and "Inter" filters to 991 rows.

**Comment by jharenza** [comment]
fixed in [a3f9dbb](https://github.com/d3b-center/annoFuse/pull/36/commits/a3f9dbbd7b187485f87caf27f98c6b7315b710b2)
