### ISSUE TITLE
spanningDelta cutoff 100 for demo file

### ISSUE THREAD

**Issue by kgaonkar6** [d3b-center/annoFuse#60]
@kgaonkar6 
- update the demo file used in shiny_app to have cutoff of 100 (@federicomarini if I keep the file name the same in extdata it won't require any changes from your side right? )
- update default cutoff 100 in filter_fusion_QC function
- update plots with spanningdelta 100 cutoff for main figure

**Comment by federicomarini** [comment]
> update the demo file used in shiny_app to have cutoff of 100 (@federicomarini if I keep the file name the same in extdata it won't require any changes from your side right? )

It should be all good if it stays the same and only the content changes 😉

**Comment by federicomarini** [comment]
Looks like this can be closed I guess @kgaonkar6 ?

**Comment by jharenza** [comment]
yup closed with #63
