### ISSUE TITLE
update instructions for filtering of numeric columns

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#61]
Sliding scales currently, hard to select 1 number for filtering, but can be achieved by `10 … 10`

**Comment by federicomarini** [comment]
Can this be considered as done in `exemplary` with the edits finalized in https://github.com/d3b-center/annoFuse/commit/0c7a459c167800a195b696fe60210d17595b06b2?

**Comment by jharenza** [comment]
yes! thanks
