### ISSUE TITLE
cleanup of gene reference lists

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#62]
- [ ] https://github.com/d3b-center/annoFuse/blob/master/inst/extdata/genelistreference.txt has rownames - remove
- [ ] https://github.com/d3b-center/annoFuse/blob/master/inst/extdata/fusionreference.txt has filenames but files not in repo; also has rownames -> add files? remove rownames
- [ ] add headers to files of gene/fusion files to add source info

**Comment by kgaonkar6** [comment]
These files form the reference files
[kinases](http://kinase.com/human/kinome/tables/Kincat_Hsap.08.02.xls)
[oncogenes](http://www.bushmanlab.org/assets/doc/allOnco_Feb2017.tsv)
[tumor suppressors](https://bioinfo.uth.edu/TSGene/Human_TSGs.txt?csrt=5027697123997809089)
curated transcription factors [@doi:10.1016/j.cell.2018.01.029]
[COSMIC genes](https://cancer.sanger.ac.uk/census)
[TCGA fusions](https://tumorfusions.org/PanCanFusV2/downloads/pancanfus.txt.gz) 
_MYBL1_ [@doi:10.1073/pnas.1300252110], _SNCAIP_ [@doi:10.1038/nature11327], _FOXR2_ [@doi:10.1016/j.cell.2016.01.015], _TTYH1_ [@doi:10.1038/ng.2849], and _TERT_ [@doi:10.1038/ng.3438; @doi:10.1002/gcc.22110; @doi:10.1016/j.canlet.2014.11.057; @doi:10.1007/s11910-017-0722-5] were added to the oncogene list and _BCOR_ [@doi:10.1016/j.cell.2016.01.015] and _QKI_ [@doi:10.1038/ng.3500] were added to the tumor suppressor gene list based on pediatric cancer literature review.


Do we need to add the files, I think linking the files should be ok? However the formats are all different in the linked files so a code was used to update to this format

**Comment by jharenza** [comment]
Nope, I just added them to the markdown table in [this comment](https://github.com/d3b-center/annoFuse/pull/64#discussion_r489077859) - that should suffice

**Comment by kgaonkar6** [comment]
updated the files , ie. without rownames in yesterday's PR is in exemplary
