### ISSUE TITLE
update conjoin genes filter

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#68]
Remove this filter

**Comment by kgaonkar6** [comment]
I'm adding checkboxes let me know if I missed anything

- [x] Figure 1
- [x] Figure2
- [x] Figure3
- [x] Figure4

- [x] S1
- [x] S2
- [x] S3
- [x] S4

- [x] Table 3
- [x] Table 4

- [x] Update sensitivity in draft in PPTC/TCGA if changed
- [x] Update TCGA notebook (maybe singleSample is ok as is as an example ? )

**Comment by kgaonkar6** [comment]
DDX58--TOPORS is the only ConjoinG fusion in TCGA that was captured, which is not found in final fusion calls in the publication.

No updates to PPTC/TCGA overlaps so no update to Table3 and Table4

**Comment by kgaonkar6** [comment]
completed
