### ISSUE TITLE
add authors to package

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#72]
Update description with package authors:

Authors@R: c(person("Krutika", "S.", "Gaonkar", role = c("aut", "cre"), 
    email = "gaonkark@chop.email.edu",
    comment = c(ORCID = "0000-0003-0838-2405")),
    person("Federico", "Marini", role = "aut", 
    email = "marinif@uni-mainz.de",
    comment = c(ORCID = "0000-0003-3252-7758")),
    person("Komal", "S.", "Rathi", role = "ctb", 
    email = "rathik@email.chop.edu",
    comment = c(ORCID = "0000-0001-5534-6904")),
    person("Jaclyn", "N.", "Taroni", role = "ctb", 
    email = "jaclyn.taroni@ccdatalab.org",
    comment = c(ORCID = "0000-0003-4734-4508")))

@federicomarini - I switched you from `ctb` to `aut` because using[ this guidance](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf), you had substantial contributions with shinyFuse and reportFuse.

**Comment by federicomarini** [comment]
Thanks!
Back then it was indeed just some input, I wish more and more of fruitful collaborations pop up - take that, 2020!

**Comment by jharenza** [comment]
closed with #73
