### ISSUE TITLE
cleanup DS_store and license files

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#8]
Delete DS_store and remove one of the license files
Rproj.user folder needs to be removed
Clean up doc and build vignettes from them

**Comment by federicomarini** [comment]
It looks like correct to specify the LICENSE with the double file (one is just a one liner, the second comes in with the bulk of text) - If I recall correctly, this is also the proposed approach via `usethis`

I think also the .Rproj.user folder needs to be removed to have a cleanest root folder 😉

**Comment by federicomarini** [comment]
(I can work on these already in the fork and throw in a PR)

**Comment by federicomarini** [comment]
Ideally, the content of `doc` could be an excellent basis to build up some more vignettes 😉

**Comment by federicomarini** [comment]
cleanup of vignettes folder also done 😉

**Comment by federicomarini** [comment]
I think this one can be safely closed, checking in with @kgaonkar6 to be 100% safe!

**Comment by kgaonkar6** [comment]
Yes looks like it can be closed
