### ISSUE TITLE
Bug: missing ref files and shinyFuse demo file

### ISSUE THREAD

**Issue by jharenza** [d3b-center/annoFuse#90]
#### Provide the command used or report the bug here
Was searching for our demo data (putative oncogenic file we use for shinyfuse) and noticed it, along with the reference folder are missing.

#### What version are you using?

Current master 

#### Add error message here (if applicable)
NA

#### Add Session info
Run `sessionInfo()` and post the output below
NA

**Comment by federicomarini** [comment]
Hi Jo Lynne, in the current version on `master` is using already the structure with the separate data-centered repository, see https://github.com/d3b-center/annoFuse/blob/92cdd6975d6db84a692ad1bd631fa7db9834003d/DESCRIPTION#L24

You can find these files in the respective folder of https://github.com/federicomarini/annoFuseData

The reason behind this split is the size limitation we would incur into when submitting to Bioconductor (they want us to aim for max. 5 Mb)

Hope it clarifies the situation 😉 
Federico

**Comment by federicomarini** [comment]
Side note: the repo's ownership can be transferred anytime to the `d3b-center` organisation on GitHub, if you prefer so!

**Comment by jharenza** [comment]
Oh great- i like it. I think we need to update some readme links then as well because they point to the old structure.

**Comment by federicomarini** [comment]
I'll look into that - I was sure I did replace all relevant occurrencies in the code part (otherwise R CMD check is a careful complainer!).

Shall I transfer the ownership already now @jharenza ? Once that is done, it makes sense to update the links just once 😉

**Comment by jharenza** [comment]
> Shall I transfer the ownership already now @jharenza ? Once that is done, it makes sense to update the links just once 😉

sure, thanks!

**Comment by federicomarini** [comment]
Looks like I need some extra permissions to create it over there:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7447478/115282518-9686ca80-a14a-11eb-97e3-0507cd24c36d.png">

Otherwise: I'll transfer this to you, and you transfer it to `d3b-center`? Sorry for the extra hassle.

**Comment by jharenza** [comment]
you can transfer to me and I will transfer, thanks!

**Comment by jharenza** [comment]
https://github.com/d3b-center/annoFuseData transferred!

**Comment by jharenza** [comment]
closed with #91
