### ISSUE TITLE
Bug: Files missing from inst/extdata on master

### ISSUE THREAD

**Issue by sickler-alex** [d3b-center/annoFuse#96]
#### Provide the command used or report the bug here

On the `v0.90.0` branch, there are files in the inst/extdata that aren't on the master branch. When installing using the command in the README, it defaults to the master branch and would not download those files. This is particularly an issue in [OpenTargets LGAT subtyping](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-LGAT/03-subset-cnv-files-LGAT.Rmd) where the pfamDataBioMart.RDS file is being read. One solution might be to update the installation command README to point to the current `v0.90.0` branch, but this will need to be updated with future versions.

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by jharenza** [comment]
@federicomarini could you possibly look into the way that the data is being downloaded with the new data repo - maybe we need to change some commands for this?

**Comment by federicomarini** [comment]
I'll revisit this once back from the holiday, should be easy to update if needed!

**Comment by komalsrathi** [comment]
@federicomarini any idea how I can access pfamDataBioMart.RDS? I am facing the same issue as @sickler-alex.

**Comment by federicomarini** [comment]
Hi @komalsrathi , the file you look for is in the companion package, handling the data required, `annoFuseData`.
You can access it from here: https://github.com/d3b-center/annoFuseData/tree/master/inst/extdata

The ongoing dev efforts will simply depend on this package, and will make the retrieval pretty much seamless for the end user - only thing that will change is basically behind the curtains
